---
- name: debian | install imagick module for php
  apt: name={{apt_package}} state=installed

- name: debian | enable imagick module for php
  command: php5enmod {{php_imagick_ini_filename}}
  args:
    creates: "{{ansible_local.phpinfo_core.php_config_file_scan_dir}}/{{php_imagick_extension_priority}}-{{php_imagick_ini_filename}}.ini"
